#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

echo "Updating package lists and installing prerequisites..."
sudo apt-get update -y
sudo apt-get install -y ca-certificates curl gnupg lsb-release

sudo install -m 0755 -d /etc/apt/keyrings

sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.gpg
sudo chmod a+r /etc/apt/keyrings/docker.gpg

## install based on the unbutntu version
ARCH=$(dpkg --print-architecture)
VERSION_CODENAME=$(lsb_release -cs)
echo "deb [arch=$ARCH signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $VERSION_CODENAME stable" \
    | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null


sudo apt-get update -y
sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

if ! getent group docker >/dev/null; then
    sudo groupadd docker
fi
sudo usermod -aG docker $USER


docker_version=$(docker --version 2>/dev/null || echo "not installed")
if [ "$docker_version" != "not installed" ]; then
    echo "Docker installed successfully: $docker_version"
else
    echo "Docker installation failed."
    exit 1
fi

